### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by TATyKeFei** [NotSabrina/BiomesTitle#1]
i don't speak English, so I don't know can you understand the machine translation
This plugin looks great, but I think there's room for improvement

Can you also support actionbar and [Terra](https://www.spigotmc.org/resources/terra.85151/) 's bioms?
Reload the plugin and disable the title function in different worlds
thank you

**Comment by NotSabrina** [comment]
I'l try

**Comment by NotSabrina** [comment]
actionbar added but for Terra not added because the API not release yet

**Comment by TATyKeFei** [comment]
ok, thank you!

**Comment by TATyKeFei** [comment]
Hi, I found a wiki about custom biomes that seems to be implemented using data_pack and can make BiomesTitle support custom Biomes without using the Terra api
`https://minecraft.fandom.com/wiki/Custom_biome`

**Comment by NotSabrina** [comment]
所以如果terra 改變了F3 中的生物群系，它應該可以毫無問題地與我的插件一起使用，只需找到terra 生物群落名稱然後將其添加到配置中，如果terra 生物群落改變F3 中的生物群系，它應該可以工作（Google翻譯）

**Comment by NotSabrina** [comment]
讓我知道它是否有效（Google翻譯）
