### ISSUE TITLE
support placeholderapi!!!!

### ISSUE THREAD

**Issue by TATyKeFei** [NotSabrina/BiomesTitle#2]
Can you support placeholderapi?
I want to let font image work in the plugin, it can let biometitle cool more very much !!
like this
![image](https://github.com/NotSabrina/BiomesTitle/assets/125815900/d9dd6c0e-0a44-44a0-88b7-995682892806)

**Comment by NotSabrina** [comment]
i`l try

**Comment by TATyKeFei** [comment]
Thanks, it can works!

**Comment by NotSabrina** [comment]
該插件沒有掛鉤 PlaceholderAPI 它是如何工作的?

**Comment by TATyKeFei** [comment]
I configured it that way, but it worked
```
  FOREST:
    message: "&f%img_forest_biomes%"
    display: "title"
```
![image](https://github.com/NotSabrina/BiomesTitle/assets/125815900/ad86d250-3b1e-486d-9324-4831bf919d77)
I tried other placeholders and they worked
```
  FOREST:
    message: "&f%player_name% 你进入了&a&l森林&r!"
    display: "title"
```
![image](https://github.com/NotSabrina/BiomesTitle/assets/125815900/566dadc4-c944-4eb9-b1da-8ab2880cc8f1)
